Comment out GPU related scheduled tests due to contrained resources

diff --git a/.github/workflows/jax-nightly-scheduler.yaml b/.github/workflows/jax-nightly-scheduler.yaml
--- a/.github/workflows/jax-nightly-scheduler.yaml
+++ b/.github/workflows/jax-nightly-scheduler.yaml
@@ -70,66 +70,66 @@ jobs:
           gh run watch "$RUN_ID" --interval 180
    
   
-  run-gpu-single-host-training-test:
-    runs-on: ubuntu-latest
-    needs: run-tpu-multi-slices-training-test
-    if: always()
-    permissions:
-      actions: write
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  # run-gpu-single-host-training-test:
+  #   runs-on: ubuntu-latest
+  #   needs: run-tpu-multi-slices-training-test
+  #   if: always()
+  #   permissions:
+  #     actions: write
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
       
-      - name: Run JAX Nightly Sequence Training Tests
-        env: 
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          set -e
-          echo "Triggering workflow: gpu-training-test.yaml"
-          gh workflow run gpu-training-test.yaml --ref jax_nightly_py3.12
+  #     - name: Run JAX Nightly Sequence Training Tests
+  #       env: 
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         set -e
+  #         echo "Triggering workflow: gpu-training-test.yaml"
+  #         gh workflow run gpu-training-test.yaml --ref jax_nightly_py3.12
 
-          echo "Waiting 30 seconds for the new run to be registered with the API..."
-          sleep 30
+  #         echo "Waiting 30 seconds for the new run to be registered with the API..."
+  #         sleep 30
 
-          echo "Fetching the ID of the new run..."
-          RUN_ID=$(gh run list --workflow="gpu-training-test.yaml" --branch jax_nightly_py3.12 --limit 1 --json databaseId -q '.[0].databaseId')
+  #         echo "Fetching the ID of the new run..."
+  #         RUN_ID=$(gh run list --workflow="gpu-training-test.yaml" --branch jax_nightly_py3.12 --limit 1 --json databaseId -q '.[0].databaseId')
 
-          if [ -z "$RUN_ID" ]; then
-            echo "Error: Could not find a recent run for the workflow."
-            exit 1
-          fi
+  #         if [ -z "$RUN_ID" ]; then
+  #           echo "Error: Could not find a recent run for the workflow."
+  #           exit 1
+  #         fi
 
-          echo "Found run ID: $RUN_ID. Waiting for it to complete... every 3 mins"
-          gh run watch "$RUN_ID" --interval 180
+  #         echo "Found run ID: $RUN_ID. Waiting for it to complete... every 3 mins"
+  #         gh run watch "$RUN_ID" --interval 180
   
-  run-gpu-multi-hosts-training-test:
-    runs-on: ubuntu-latest
-    needs: run-gpu-single-host-training-test
-    if: always()
-    permissions:
-      actions: write
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  # run-gpu-multi-hosts-training-test:
+  #   runs-on: ubuntu-latest
+  #   needs: run-gpu-single-host-training-test
+  #   if: always()
+  #   permissions:
+  #     actions: write
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
       
-      - name: Run JAX Nightly Sequence Training Tests
-        env: 
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          set -e
-          echo "Triggering workflow: gpu-multihost-training-test.yaml"
-          gh workflow run gpu-multihost-training-test.yaml --ref jax_nightly_py3.12
+  #     - name: Run JAX Nightly Sequence Training Tests
+  #       env: 
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         set -e
+  #         echo "Triggering workflow: gpu-multihost-training-test.yaml"
+  #         gh workflow run gpu-multihost-training-test.yaml --ref jax_nightly_py3.12
 
-          echo "Waiting 30 seconds for the new run to be registered with the API..."
-          sleep 30
+  #         echo "Waiting 30 seconds for the new run to be registered with the API..."
+  #         sleep 30
 
-          echo "Fetching the ID of the new run..."
-          RUN_ID=$(gh run list --workflow="gpu-multihost-training-test.yaml" --branch jax_nightly_py3.12 --limit 1 --json databaseId -q '.[0].databaseId')
+  #         echo "Fetching the ID of the new run..."
+  #         RUN_ID=$(gh run list --workflow="gpu-multihost-training-test.yaml" --branch jax_nightly_py3.12 --limit 1 --json databaseId -q '.[0].databaseId')
 
-          if [ -z "$RUN_ID" ]; then
-            echo "Error: Could not find a recent run for the workflow."
-            exit 1
-          fi
+  #         if [ -z "$RUN_ID" ]; then
+  #           echo "Error: Could not find a recent run for the workflow."
+  #           exit 1
+  #         fi
 
-          echo "Found run ID: $RUN_ID. Waiting for it to complete... every 3 mins"
-          gh run watch "$RUN_ID" --interval 180
+  #         echo "Found run ID: $RUN_ID. Waiting for it to complete... every 3 mins"
+  #         gh run watch "$RUN_ID" --interval 180
